# Generated by Django 5.2.17 on 2026-09-30 21:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CAD', 'Canadian dollar'), ('AUD', 'Australian dollar'), ('INR', 'Indian rupee'), ('JPY', 'Japanese yen'), ('CHF', 'Swiss franc'), ('NZD', 'New Zealand dollar')], default='USD', max_length=3)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('housing', 'Housing'), ('food', 'Food'), ('transport', 'Transport'), ('health', 'Health'), ('education', 'Education'), ('bills', 'Bills'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('gift', 'Gift'), ('other', 'Other')], default='other', max_length=16)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='finance_fin_user_id_2cac0d_idx'), models.Index(fields=['user', 'kind', 'date'], name='finance_fin_user_id_769252_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_amount_positive')],
            },
        ),
    ]
