# Generated by Django 5.2.17 on 2026-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financetransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CAD', 'Canadian dollar'), ('AUD', 'Australian dollar'), ('INR', 'Indian rupee'), ('JPY', 'Japanese yen'), ('CHF', 'Swiss franc'), ('NZD', 'New Zealand dollar'), ('KES', 'Kenyan shilling')], default='USD', max_length=3),
        ),
    ]
