# Generated by Django 5.2.17 on 2026-10-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_privatepdfupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardentry',
            name='kind',
            field=models.CharField(choices=[('diary', 'Diary entry'), ('note', 'Note'), ('resource', 'Learning resource'), ('project', 'Project'), ('goal', 'Goal'), ('achievement', 'Achievement'), ('memory', 'Memory'), ('entertainment', 'Entertainment'), ('idea', 'Idea')], db_index=True, max_length=20),
        ),
    ]
